[project]
name = "amtb-mcp"
version = "0.1.0"
description = "MCP server for communicating with AMTB"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.4",
]

[tool.uv.workspace]
members = [
    "amtb-mcp",
]
